src/java/controlador/EventoParticipantesController.java
package controlador;

import entidad.EventoParticipantes;
import controlador.util.JsfUtil;
import controlador.util.PaginationHelper;
import sesion.EventoParticipantesFacade;

import java.io.Serializable;
import java.util.ResourceBundle;
import javax.ejb.EJB;
import javax.faces.bean.ManagedBean;
import javax.faces.bean.SessionScoped;
import javax.faces.component.UIComponent;
import javax.faces.context.FacesContext;
import javax.faces.convert.Converter;
import javax.faces.convert.FacesConverter;
import javax.faces.model.DataModel;
import javax.faces.model.ListDataModel;
import javax.faces.model.SelectItem;

@ManagedBean(name = "eventoParticipantesController")
@SessionScoped
public class EventoParticipantesController implements Serializable {

    private EventoParticipantes current;
    private DataModel items = null;
    @EJB
    private sesion.EventoParticipantesFacade ejbFacade;
    private PaginationHelper pagination;
    private int selectedItemIndex;

    public EventoParticipantesController() {
    }

    public EventoParticipantes getSelected() {
        if (current == null) {
            current = new EventoParticipantes();
            selectedItemIndex = -1;
        }
        return current;
    }

    private EventoParticipantesFacade getFacade() {
        return ejbFacade;
    }

    public PaginationHelper getPagination() {
        if (pagination == null) {
            pagination = new PaginationHelper(10) {

                @Override
                public int getItemsCount() {
                    return getFacade().count();
                }

                @Override
                public DataModel createPageDataModel() {
                    return new ListDataModel(getFacade().findRange(new int[]{getPageFirstItem(), getPageFirstItem() + getPageSize()}));
                }
            };
        }
        return pagination;
    }

    public String prepareList() {
        recreateModel();
        return "List";
    }

    public String prepareView() {
        current = (EventoParticipantes) getItems().getRowData();
        selectedItemIndex = pagination.getPageFirstItem() + getItems().getRowIndex();
        return "View";
    }

    public String prepareCreate() {
        current = new EventoParticipantes();
        selectedItemIndex = -1;
        return "Create";
    }

    public String create() {
        try {
            getFacade().create(current);
            JsfUtil.addSuccessMessage(ResourceBundle.getBundle("/agenda1").getString("EventoParticipantesCreated"));
            return prepareCreate();
        } catch (Exception e) {
            JsfUtil.addErrorMessage(e, ResourceBundle.getBundle("/agenda1").getString("PersistenceErrorOccured"));
            return null;
        }
    }

    public String prepareEdit() {
        current = (EventoParticipantes) getItems().getRowData();
        selectedItemIndex = pagination.getPageFirstItem() + getItems().getRowIndex();
        return "Edit";
    }

    public String update() {
        try {
            getFacade().edit(current);
            JsfUtil.addSuccessMessage(ResourceBundle.getBundle("/agenda1").getString("EventoParticipantesUpdated"));
            return "View";
        } catch (Exception e) {
            JsfUtil.addErrorMessage(e, ResourceBundle.getBundle("/agenda1").getString("PersistenceErrorOccured"));
            return null;
        }
    }

    public String destroy() {
        current = (EventoParticipantes) getItems().getRowData();
        selectedItemIndex = pagination.getPageFirstItem() + getItems().getRowIndex();
        performDestroy();
        recreatePagination();
        recreateModel();
        return "List";
    }

    public String destroyAndView() {
        performDestroy();
        recreateModel();
        updateCurrentItem();
        if (selectedItemIndex >= 0) {
            return "View";
        } else {
            // all items were removed - go back to list
            recreateModel();
            return "List";
        }
    }

    private void performDestroy() {
        try {
            getFacade().remove(current);
            JsfUtil.addSuccessMessage(ResourceBundle.getBundle("/agenda1").getString("EventoParticipantesDeleted"));
        } catch (Exception e) {
            JsfUtil.addErrorMessage(e, ResourceBundle.getBundle("/agenda1").getString("PersistenceErrorOccured"));
        }
    }

    private void updateCurrentItem() {
        int count = getFacade().count();
        if (selectedItemIndex >= count) {
            // selected index cannot be bigger than number of items:
            selectedItemIndex = count - 1;
            // go to previous page if last page disappeared:
            if (pagination.getPageFirstItem() >= count) {
                pagination.previousPage();
            }
        }
        if (selectedItemIndex >= 0) {
            current = getFacade().findRange(new int[]{selectedItemIndex, selectedItemIndex + 1}).get(0);
        }
    }

    public DataModel getItems() {
        if (items == null) {
            items = getPagination().createPageDataModel();
        }
        return items;
    }

    private void recreateModel() {
        items = null;
    }

    private void recreatePagination() {
        pagination = null;
    }

    public String next() {
        getPagination().nextPage();
        recreateModel();
        return "List";
    }

    public String previous() {
        getPagination().previousPage();
        recreateModel();
        return "List";
    }

    public SelectItem[] getItemsAvailableSelectMany() {
        return JsfUtil.getSelectItems(ejbFacade.findAll(), false);
    }

    public SelectItem[] getItemsAvailableSelectOne() {
        return JsfUtil.getSelectItems(ejbFacade.findAll(), true);
    }

    @FacesConverter(forClass = EventoParticipantes.class)
    public static class EventoParticipantesControllerConverter implements Converter {

        @Override
        public Object getAsObject(FacesContext facesContext, UIComponent component, String value) {
            if (value == null || value.length() == 0) {
                return null;
            }
            EventoParticipantesController controller = (EventoParticipantesController) facesContext.getApplication().getELResolver().
                    getValue(facesContext.getELContext(), null, "eventoParticipantesController");
            return controller.ejbFacade.find(getKey(value));
        }

        java.lang.Integer getKey(String value) {
            java.lang.Integer key;
            key = Integer.valueOf(value);
            return key;
        }

        String getStringKey(java.lang.Integer value) {
            StringBuilder sb = new StringBuilder();
            sb.append(value);
            return sb.toString();
        }

        @Override
        public String getAsString(FacesContext facesContext, UIComponent component, Object object) {
            if (object == null) {
                return null;
            }
            if (object instanceof EventoParticipantes) {
                EventoParticipantes o = (EventoParticipantes) object;
                return getStringKey(o.getIdParticipante());
            } else {
                throw new IllegalArgumentException("object " + object + " is of type " + object.getClass().getName() + "; expected type: " + EventoParticipantes.class.getName());
            }
        }

    }

}

web/eventoParticipantes/Create.xhtml
<?xml version="1.0" encoding="UTF-8" ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:ui="http://xmlns.jcp.org/jsf/facelets"
      xmlns:h="http://xmlns.jcp.org/jsf/html"
      xmlns:f="http://xmlns.jcp.org/jsf/core">

    <ui:composition template="/template.xhtml">
        <ui:define name="title">
            <h:outputText value="#{agenda1.CreateEventoParticipantesTitle}"></h:outputText>
        </ui:define>
        <ui:define name="body">
            <h:panelGroup id="messagePanel" layout="block">
                <h:messages errorStyle="color: red" infoStyle="color: green" layout="table"/>
            </h:panelGroup>
            <h:form>
                <h:panelGrid columns="2">
                    <h:outputLabel value="#{agenda1.CreateEventoParticipantesLabel_idAutoRegistro}" for="idAutoRegistro" />
                    <h:selectOneMenu id="idAutoRegistro" value="#{eventoParticipantesController.selected.idAutoRegistro}" title="#{agenda1.CreateEventoParticipantesTitle_idAutoRegistro}" required="true" requiredMessage="#{agenda1.CreateEventoParticipantesRequiredMessage_idAutoRegistro}">
                        <f:selectItems value="#{autoRegistroController.itemsAvailableSelectOne}"/>
                    </h:selectOneMenu>
                    <h:outputLabel value="#{agenda1.CreateEventoParticipantesLabel_empleadosidEmpleados}" for="empleadosidEmpleados" />
                    <h:selectOneMenu id="empleadosidEmpleados" value="#{eventoParticipantesController.selected.empleadosidEmpleados}" title="#{agenda1.CreateEventoParticipantesTitle_empleadosidEmpleados}" >
                        <f:selectItems value="#{empleadosController.itemsAvailableSelectOne}"/>
                    </h:selectOneMenu>
                    <h:outputLabel value="#{agenda1.CreateEventoParticipantesLabel_eventoIdevento}" for="eventoIdevento" />
                    <h:selectOneMenu id="eventoIdevento" value="#{eventoParticipantesController.selected.eventoIdevento}" title="#{agenda1.CreateEventoParticipantesTitle_eventoIdevento}" required="true" requiredMessage="#{agenda1.CreateEventoParticipantesRequiredMessage_eventoIdevento}">
                        <f:selectItems value="#{eventoController.itemsAvailableSelectOne}"/>
                    </h:selectOneMenu>
                    <h:outputLabel value="#{agenda1.CreateEventoParticipantesLabel_proveedoresidProveedores}" for="proveedoresidProveedores" />
                    <h:selectOneMenu id="proveedoresidProveedores" value="#{eventoParticipantesController.selected.proveedoresidProveedores}" title="#{agenda1.CreateEventoParticipantesTitle_proveedoresidProveedores}" >
                        <f:selectItems value="#{proveedoresController.itemsAvailableSelectOne}"/>
                    </h:selectOneMenu>
                </h:panelGrid>
                <br />
                <h:commandLink action="#{eventoParticipantesController.create}" value="#{agenda1.CreateEventoParticipantesSaveLink}" />
                <br />
                <br />
                <h:commandLink action="#{eventoParticipantesController.prepareList}" value="#{agenda1.CreateEventoParticipantesShowAllLink}" immediate="true"/>
                <br />
                <br />
                <h:link outcome="/index" value="#{agenda1.CreateEventoParticipantesIndexLink}"/>
            </h:form>
        </ui:define>
    </ui:composition>

</html>

web/eventoParticipantes/Edit.xhtml
<?xml version="1.0" encoding="UTF-8" ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:ui="http://xmlns.jcp.org/jsf/facelets"
      xmlns:h="http://xmlns.jcp.org/jsf/html"
      xmlns:f="http://xmlns.jcp.org/jsf/core">

    <ui:composition template="/template.xhtml">
        <ui:define name="title">
            <h:outputText value="#{agenda1.EditEventoParticipantesTitle}"></h:outputText>
        </ui:define>
        <ui:define name="body">
            <h:panelGroup id="messagePanel" layout="block">
                <h:messages errorStyle="color: red" infoStyle="color: green" layout="table"/>
            </h:panelGroup>
            <h:form>
                <h:panelGrid columns="2">
                    <h:outputLabel value="#{agenda1.EditEventoParticipantesLabel_idAutoRegistro}" for="idAutoRegistro" />
                    <h:selectOneMenu id="idAutoRegistro" value="#{eventoParticipantesController.selected.idAutoRegistro}" title="#{agenda1.EditEventoParticipantesTitle_idAutoRegistro}" required="true" requiredMessage="#{agenda1.EditEventoParticipantesRequiredMessage_idAutoRegistro}">
                        <f:selectItems value="#{autoRegistroController.itemsAvailableSelectOne}"/>
                    </h:selectOneMenu>
                    <h:outputLabel value="#{agenda1.EditEventoParticipantesLabel_empleadosidEmpleados}" for="empleadosidEmpleados" />
                    <h:selectOneMenu id="empleadosidEmpleados" value="#{eventoParticipantesController.selected.empleadosidEmpleados}" title="#{agenda1.EditEventoParticipantesTitle_empleadosidEmpleados}" >
                        <f:selectItems value="#{empleadosController.itemsAvailableSelectOne}"/>
                    </h:selectOneMenu>
                    <h:outputLabel value="#{agenda1.EditEventoParticipantesLabel_eventoIdevento}" for="eventoIdevento" />
                    <h:selectOneMenu id="eventoIdevento" value="#{eventoParticipantesController.selected.eventoIdevento}" title="#{agenda1.EditEventoParticipantesTitle_eventoIdevento}" required="true" requiredMessage="#{agenda1.EditEventoParticipantesRequiredMessage_eventoIdevento}">
                        <f:selectItems value="#{eventoController.itemsAvailableSelectOne}"/>
                    </h:selectOneMenu>
                    <h:outputLabel value="#{agenda1.EditEventoParticipantesLabel_proveedoresidProveedores}" for="proveedoresidProveedores" />
                    <h:selectOneMenu id="proveedoresidProveedores" value="#{eventoParticipantesController.selected.proveedoresidProveedores}" title="#{agenda1.EditEventoParticipantesTitle_proveedoresidProveedores}" >
                        <f:selectItems value="#{proveedoresController.itemsAvailableSelectOne}"/>
                    </h:selectOneMenu>
                </h:panelGrid>
                <h:commandLink action="#{eventoParticipantesController.update}" value="#{agenda1.EditEventoParticipantesSaveLink}"/>
                <br />
                <br />
                <h:link outcome="View" value="#{agenda1.EditEventoParticipantesViewLink}"/>
                <br />
                <h:commandLink action="#{eventoParticipantesController.prepareList}" value="#{agenda1.EditEventoParticipantesShowAllLink}" immediate="true"/>
                <br />
                <br />
                <h:link outcome="/index" value="#{agenda1.EditEventoParticipantesIndexLink}" />
            </h:form>
        </ui:define>
    </ui:composition>

</html>

web/eventoParticipantes/List.xhtml
<?xml version="1.0" encoding="UTF-8" ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:ui="http://xmlns.jcp.org/jsf/facelets"
      xmlns:h="http://xmlns.jcp.org/jsf/html"
      xmlns:f="http://xmlns.jcp.org/jsf/core">

    <ui:composition template="/template.xhtml">
        <ui:define name="title">
            <h:outputText value="#{agenda1.ListEventoParticipantesTitle}"></h:outputText>
        </ui:define>
        <ui:define name="body">
            <h:form styleClass="jsfcrud_list_form">
                <h:panelGroup id="messagePanel" layout="block">
                    <h:messages errorStyle="color: red" infoStyle="color: green" layout="table"/>
                </h:panelGroup>
                <h:outputText escape="false" value="#{agenda1.ListEventoParticipantesEmpty}" rendered="#{eventoParticipantesController.items.rowCount == 0}"/>
                <h:panelGroup rendered="#{eventoParticipantesController.items.rowCount > 0}">
                    <h:outputText value="#{eventoParticipantesController.pagination.pageFirstItem + 1}..#{eventoParticipantesController.pagination.pageLastItem + 1}/#{eventoParticipantesController.pagination.itemsCount}"/>&nbsp;
                    <h:commandLink action="#{eventoParticipantesController.previous}" value="#{agenda1.Previous} #{eventoParticipantesController.pagination.pageSize}" rendered="#{eventoParticipantesController.pagination.hasPreviousPage}"/>&nbsp;
                    <h:commandLink action="#{eventoParticipantesController.next}" value="#{agenda1.Next} #{eventoParticipantesController.pagination.pageSize}" rendered="#{eventoParticipantesController.pagination.hasNextPage}"/>&nbsp;
                    <h:dataTable value="#{eventoParticipantesController.items}" var="item" border="0" cellpadding="2" cellspacing="0" rowClasses="jsfcrud_odd_row,jsfcrud_even_row" rules="all" style="border:solid 1px">
                        <h:column>
                            <f:facet name="header">
                                <h:outputText value="#{agenda1.ListEventoParticipantesTitle_idParticipante}"/>
                            </f:facet>
                            <h:outputText value="#{item.idParticipante}"/>
                        </h:column>
                        <h:column>
                            <f:facet name="header">
                                <h:outputText value="#{agenda1.ListEventoParticipantesTitle_idAutoRegistro}"/>
                            </f:facet>
                            <h:outputText value="#{item.idAutoRegistro}"/>
                        </h:column>
                        <h:column>
                            <f:facet name="header">
                                <h:outputText value="#{agenda1.ListEventoParticipantesTitle_empleadosidEmpleados}"/>
                            </f:facet>
                            <h:outputText value="#{item.empleadosidEmpleados}"/>
                        </h:column>
                        <h:column>
                            <f:facet name="header">
                                <h:outputText value="#{agenda1.ListEventoParticipantesTitle_eventoIdevento}"/>
                            </f:facet>
                            <h:outputText value="#{item.eventoIdevento}"/>
                        </h:column>
                        <h:column>
                            <f:facet name="header">
                                <h:outputText value="#{agenda1.ListEventoParticipantesTitle_proveedoresidProveedores}"/>
                            </f:facet>
                            <h:outputText value="#{item.proveedoresidProveedores}"/>
                        </h:column>
                        <h:column>
                            <f:facet name="header">
                                <h:outputText value="&nbsp;"/>
                            </f:facet>
                            <h:commandLink action="#{eventoParticipantesController.prepareView}" value="#{agenda1.ListEventoParticipantesViewLink}"/>
                            <h:outputText value=" "/>
                            <h:commandLink action="#{eventoParticipantesController.prepareEdit}" value="#{agenda1.ListEventoParticipantesEditLink}"/>
                            <h:outputText value=" "/>
                            <h:commandLink action="#{eventoParticipantesController.destroy}" value="#{agenda1.ListEventoParticipantesDestroyLink}"/>
                        </h:column>
                    </h:dataTable>
                </h:panelGroup>
                <br />
                <h:commandLink action="#{eventoParticipantesController.prepareCreate}" value="#{agenda1.ListEventoParticipantesCreateLink}"/>
                <br />
                <br />
                <h:link outcome="/index" value="#{agenda1.ListEventoParticipantesIndexLink}"/>
            </h:form>
        </ui:define>
    </ui:composition>

</html>

web/eventoParticipantes/View.xhtml
<?xml version="1.0" encoding="UTF-8" ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:ui="http://xmlns.jcp.org/jsf/facelets"
      xmlns:h="http://xmlns.jcp.org/jsf/html"
      xmlns:f="http://xmlns.jcp.org/jsf/core">

    <ui:composition template="/template.xhtml">
        <ui:define name="title">
            <h:outputText value="#{agenda1.ViewEventoParticipantesTitle}"></h:outputText>
        </ui:define>
        <ui:define name="body">
            <h:panelGroup id="messagePanel" layout="block">
                <h:messages errorStyle="color: red" infoStyle="color: green" layout="table"/>
            </h:panelGroup>
            <h:form>
                <h:panelGrid columns="2">
                    <h:outputText value="#{agenda1.ViewEventoParticipantesLabel_idParticipante}"/>
                    <h:outputText value="#{eventoParticipantesController.selected.idParticipante}" title="#{agenda1.ViewEventoParticipantesTitle_idParticipante}"/>
                    <h:outputText value="#{agenda1.ViewEventoParticipantesLabel_idAutoRegistro}"/>
                    <h:outputText value="#{eventoParticipantesController.selected.idAutoRegistro}" title="#{agenda1.ViewEventoParticipantesTitle_idAutoRegistro}"/>
                    <h:outputText value="#{agenda1.ViewEventoParticipantesLabel_empleadosidEmpleados}"/>
                    <h:outputText value="#{eventoParticipantesController.selected.empleadosidEmpleados}" title="#{agenda1.ViewEventoParticipantesTitle_empleadosidEmpleados}"/>
                    <h:outputText value="#{agenda1.ViewEventoParticipantesLabel_eventoIdevento}"/>
                    <h:outputText value="#{eventoParticipantesController.selected.eventoIdevento}" title="#{agenda1.ViewEventoParticipantesTitle_eventoIdevento}"/>
                    <h:outputText value="#{agenda1.ViewEventoParticipantesLabel_proveedoresidProveedores}"/>
                    <h:outputText value="#{eventoParticipantesController.selected.proveedoresidProveedores}" title="#{agenda1.ViewEventoParticipantesTitle_proveedoresidProveedores}"/>
                </h:panelGrid>
                <br />
                <h:commandLink action="#{eventoParticipantesController.destroyAndView}" value="#{agenda1.ViewEventoParticipantesDestroyLink}"/>
                <br />
                <br />
                <h:link outcome="Edit" value="#{agenda1.ViewEventoParticipantesEditLink}"/>
                <br />
                <h:commandLink action="#{eventoParticipantesController.prepareCreate}" value="#{agenda1.ViewEventoParticipantesCreateLink}" />
                <br />
                <h:commandLink action="#{eventoParticipantesController.prepareList}" value="#{agenda1.ViewEventoParticipantesShowAllLink}"/>
                <br />
                <br />
                <h:link outcome="/index" value="#{agenda1.ViewEventoParticipantesIndexLink}"/>

            </h:form>
        </ui:define>
    </ui:composition>

</html>